//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLogsPaytmHook
    {
        public int AppLogsPaytmHookId { get; set; }
        public string InputPaytm { get; set; }
        public string PtmOrderId { get; set; }
        public Nullable<int> LinkOrderId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string PtmStatus { get; set; }
        public string SendStatus { get; set; }
        public Nullable<int> PtmLinkId { get; set; }
        public string TxnId { get; set; }
        public string TxnAmount { get; set; }
        public string PtmRespMsg { get; set; }
        public string LinkNotes { get; set; }
        public string CheckSumHash { get; set; }
        public string MachineName { get; set; }
    }
}
