//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int Id { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string Message { get; set; }
        public string Error { get; set; }
        public string MachineName { get; set; }
    }
}
