//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallbackPushApi
    {
        public int CallbackPushApiId { get; set; }
        public string customer_number { get; set; }
        public string uuid { get; set; }
        public string agent_number { get; set; }
        public string call_duration { get; set; }
        public Nullable<int> id { get; set; }
        public string call_recording { get; set; }
        public string knowlarity_number { get; set; }
        public string call_time { get; set; }
        public Nullable<System.DateTime> call_date { get; set; }
        public string call_status { get; set; }
        public string call_transfer_status { get; set; }
        public string conversation_duration { get; set; }
    }
}
