//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallAgentDetails
    {
        public int LoginId { get; set; }
        public System.TimeSpan LoginTime { get; set; }
        public System.TimeSpan AvailableTime { get; set; }
        public System.TimeSpan OnCallTime { get; set; }
        public System.TimeSpan BreakTime { get; set; }
        public System.TimeSpan TimeToAnswer { get; set; }
        public System.TimeSpan AvgTalkTime { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string Attendance { get; set; }
        public Nullable<int> AnsweredCalls { get; set; }
    
        public virtual CallAgentMaster CallAgentMaster { get; set; }
    }
}
