//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallAgentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallAgentMaster()
        {
            this.CallAgentDetails = new HashSet<CallAgentDetails>();
            this.CallAgentReporting = new HashSet<CallAgentReporting>();
            this.CallAgentReporting1 = new HashSet<CallAgentReporting>();
        }
    
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string CompanyEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallAgentDetails> CallAgentDetails { get; set; }
        public virtual RUser RUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallAgentReporting> CallAgentReporting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallAgentReporting> CallAgentReporting1 { get; set; }
    }
}
