//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelOption
    {
        public int CancelOptionId { get; set; }
        public string OptionItem { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
