//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFreePay
    {
        public int CashFreePayId { get; set; }
        public string InputValue { get; set; }
        public string VenderOutput { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<int> OrderModifyId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Amt { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
