//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using Newtonsoft.Json;
    using RainbowWine.Services;
    using System;
    using System.Collections.Generic;
    
    public partial class CashFreeRefund
    {
        public int CashFreeRefundId { get; set; }
        public Nullable<int> IssueId { get; set; }
        public Nullable<int> OrderModifyId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string InputParam { get; set; }
        public string VenderOutput { get; set; }
        public string Amt { get; set; }
        public CashFreeRefundObject RefundParam { get {
               
                if (InputParam == null)
                {
                    return null;
                }
                return JsonConvert.DeserializeObject<CashFreeRefundObject>(InputParam );
            } }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
