//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContact1 { get; set; }
        public string CustAddr { get; set; }
        public string CustPlaceId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string CallerAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
