//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAgent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryAgent()
        {
            this.DeliveryAgentLogins = new HashSet<DeliveryAgentLogin>();
            this.DumpRoutePlans = new HashSet<DumpRoutePlan>();
            this.RoutePlans = new HashSet<RoutePlan>();
            this.RUsers = new HashSet<RUser>();
        }
    
        public int Id { get; set; }
        public string DeliveryExecName { get; set; }
        public int ShopID { get; set; }
        public Nullable<System.DateTime> LastDeliveryOn { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string TravelMode { get; set; }
        public string Coverage { get; set; }
        public Nullable<int> DeliverySlotID { get; set; }
        public Nullable<bool> IsAtShop { get; set; }
        public string ExciseID { get; set; }
        public string DocPath { get; set; }
        public Nullable<bool> Present { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string DelType { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<int> DeliveryAgentTypeId { get; set; }
        public string WeekOffs { get; set; }
        public Nullable<bool> HTrackDisallow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryAgentLogin> DeliveryAgentLogins { get; set; }
        public virtual DeliverySlot DeliverySlot { get; set; }
        public virtual DeliveryZone DeliveryZone { get; set; }
        public virtual WineShop WineShop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DumpRoutePlan> DumpRoutePlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutePlan> RoutePlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUser> RUsers { get; set; }
        public virtual DeliveryAgentType DeliveryAgentType { get; set; }
    }
}
