//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelIncentiveConfig
    {
        public int Id { get; set; }
        public int ShopID { get; set; }
        public int ZoneID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int TimeStart { get; set; }
        public int TimeEnd { get; set; }
        public double Commission { get; set; }
        public bool isDelete { get; set; }
    }
}
