//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryPayment
    {
        public int DeliveryPaymentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> DeliveryAgentId { get; set; }
        public string JobId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<double> AmountPaid { get; set; }
        public Nullable<bool> DelPaymentConfirm { get; set; }
        public Nullable<bool> ShopAcknowledgement { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
