//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNotificationFCM
    {
        public int Id { get; set; }
        public int DeliveryAgentId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string NotificationType { get; set; }
        public bool isRead { get; set; }
        public bool isDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int PageId { get; set; }
        public string IconUrl { get; set; }
    }
}
