//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelManageShop
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        public string rUserId { get; set; }
        public int UserType { get; set; }
    }
}
