//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DumpRoutePlan
    {
        public int id { get; set; }
        public int OrderID { get; set; }
        public int ShopID { get; set; }
        public string DestPlaceID { get; set; }
        public string OrigPlaceID { get; set; }
        public int CustID { get; set; }
        public string RoutePlanLink { get; set; }
        public int OrderStatusId { get; set; }
        public System.DateTime DeliveryStart { get; set; }
        public System.DateTime DeliveryEnd { get; set; }
        public Nullable<int> DeliveryAgentId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<System.DateTime> SlotStart { get; set; }
        public Nullable<System.DateTime> SlotEnd { get; set; }
        public string JobId { get; set; }
        public Nullable<bool> isOutForDelivery { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryAgent DeliveryAgent { get; set; }
        public virtual Order Order { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual WineShop WineShop { get; set; }
    }
}
