//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftBagDetail
    {

        public GiftBagDetail()
        {
            this.GiftBagOrderItems = new HashSet<GiftBagOrderItem>();
            this.GiftBagInventorys = new HashSet<GiftBagInventory>();
            this.GiftBagOrderItemIssueDetailOriginals = new HashSet<GiftBagOrderItemIssueDetailOriginal>();
            this.GiftBagOrderItemIssueDetails = new HashSet<GiftBagOrderItemIssueDetail>();
        }
        public int GiftBagDetailId { get; set; }
        public Nullable<int> GiftBagMasterId { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string BagImageUrl { get; set; }
        public string Description { get; set; }
        public Nullable<int> OriginalPrice { get; set; }
        public Nullable<int> MRP { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }

        public virtual GiftBagMaster GiftBagMasters { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftBagOrderItem> GiftBagOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftBagInventory> GiftBagInventorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftBagOrderItemIssueDetailOriginal> GiftBagOrderItemIssueDetailOriginals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftBagOrderItemIssueDetail> GiftBagOrderItemIssueDetails { get; set; }
    }
}
