//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMixer
    {
        public int InventoryMixerId { get; set; }
        public Nullable<int> MixerDetailId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string LeadTimeKey { get; set; }
        public string LeadTimeValue { get; set; }
        public Nullable<double> DeliveryFees { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual WineShop WineShop { get; set; }
        public virtual MixerDetail MixerDetail { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
