//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MixerProductLink
    {
        public int MixerProductLinkId { get; set; }
        public Nullable<int> MixerId { get; set; }
        public Nullable<int> ProductDetailId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Mixer Mixer { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual WineShop WineShop { get; set; }
    }
}
