//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mixer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mixer()
        {
            this.MixerDetails = new HashSet<MixerDetail>();
            this.MixerProductLinks = new HashSet<MixerProductLink>();
        }
    
        public int MixerId { get; set; }
        public string MixerName { get; set; }
        public string Description { get; set; }
        public string MixerImage { get; set; }
        public string MixerThumbImage { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MixerType { get; set; }
        public Nullable<int> MixerBrandId { get; set; }
        public Nullable<double> GiftPrice { get; set; }
        public string GiftDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixerDetail> MixerDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixerProductLink> MixerProductLinks { get; set; }
    }
}
