//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MixerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MixerDetail()
        {
            this.MixerOrderItems = new HashSet<MixerOrderItem>();
            this.InventoryMixers = new HashSet<InventoryMixer>();
            this.MixerIssueDetailOriginals = new HashSet<MixerIssueDetailOriginal>();
            this.MixerIssueDetails = new HashSet<MixerIssueDetail>();
        }
    
        public int MixerDetailId { get; set; }
        public Nullable<int> MixerId { get; set; }
        public Nullable<int> MixerSizeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsShowcaseView { get; set; }
        public Nullable<int> ShopId { get; set; }
        public string MixerDetailName { get; set; }
    
        public virtual Mixer Mixer { get; set; }
        public virtual MixerSize MixerSize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixerOrderItem> MixerOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryMixer> InventoryMixers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixerIssueDetailOriginal> MixerIssueDetailOriginals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MixerIssueDetail> MixerIssueDetails { get; set; }
    }
}
