//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusMapping
    {
        public int OrderStatusMapID { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> StatusInitialID { get; set; }
        public Nullable<int> IsPaymentTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
