//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTrack
    {
        public int OrderTrackId { get; set; }
        public int OrderId { get; set; }
        public System.DateTime TrackDate { get; set; }
        public int StatusId { get; set; }
        public string LogUserId { get; set; }
        public string LogUserName { get; set; }
        public string Remark { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
