//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public int PageContentId { get; set; }
        public Nullable<int> PageVersionId { get; set; }
        public string ContentKey { get; set; }
        public string ContentValue { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
