//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageButton
    {
        public int PageButtonId { get; set; }
        public Nullable<int> PageVersionId { get; set; }
        public string ButtonKey { get; set; }
        public string ButtonType { get; set; }
        public string ButtonText { get; set; }
        public string ClickUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
