//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLinkLog
    {
        public int PaymentLinkId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string UPIString { get; set; }
        public string InputParam { get; set; }
        public string VendorOuput { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CheckSum { get; set; }
        public string PayUrlExpiry { get; set; }
        public string PtmType { get; set; }
        public Nullable<int> PtmLinkId { get; set; }
        public string PtmStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
