//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCashFreeLog
    {
        public int PaymentCashFreeLogId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string InputParameters { get; set; }
        public string VenderOutPut { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string OrderIdCF { get; set; }
        public string OrderAmount { get; set; }
        public string ReferenceId { get; set; }
        public string Status { get; set; }
        public string PaymentMode { get; set; }
        public string Msg { get; set; }
        public string TxtTime { get; set; }
        public string Signature { get; set; }
        public string SendStatus { get; set; }
        public string MachineName { get; set; }
    }
}
