//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRefund
    {
        public int PaymentRefundId { get; set; }
        public Nullable<int> AppLogsHookId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string InputParam { get; set; }
        public string VendorOuput { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TxnOrderId { get; set; }
        public string TxnTimestamp { get; set; }
        public string RefId { get; set; }
        public string RefundId { get; set; }
        public string TxnId { get; set; }
        public string TxnAmount { get; set; }
        public string RefundAmount { get; set; }
        public string TotalRefundAmount { get; set; }
        public string TxnStatus { get; set; }
        public string TxnMsg { get; set; }
        public string RefundStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
