//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PenaltyType()
        {
            this.PenaltyTransaction = new HashSet<PenaltyTransaction>();
        }
    
        public int PenaltyTypeId { get; set; }
        public string PenaltyDescription { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsPenalty { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenaltyTransaction> PenaltyTransaction { get; set; }
    }
}
