//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyTransaction
    {
        public int PenaltyTransactionId { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string UserId { get; set; }
    
        public virtual DeliveryAgent DeliveryAgents { get; set; }
        public virtual PenaltyType PenaltyType { get; set; }
    }
}
