//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRange
    {
        public int PriceRangeId { get; set; }
        public Nullable<int> StartPrice { get; set; }
        public Nullable<int> EndPrice { get; set; }
    }
}
