//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductBrandID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public string Description { get; set; }
        public string Region { get; set; }
        public string AlcoholContent { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<bool> IsPremium { get; set; }
        public string TastingNote { get; set; }
        public Nullable<bool> LaunchFlag { get; set; }
    
        public virtual ProductBrand ProductBrand { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
