//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBarcodeLink
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public string BarcodeID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
