//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSearch
    {
        public int ProductSearchId { get; set; }
        public string Id { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Region { get; set; }
        public string AlcoholContent { get; set; }
        public string BrandName { get; set; }
        public string Category { get; set; }
        public string Search { get; set; }
    }
}
