//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoApply
    {
        public int PromoApplyId { get; set; }
        public Nullable<int> PromoId { get; set; }
        public Nullable<int> ProductDetailId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual PromoCode PromoCode { get; set; }
    }
}
