//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsDetails
    {
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public string GroupOne { get; set; }
        public string GroupTwo { get; set; }
        public string IsTitle { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
