//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralUser
    {
        public int ReferralUserId { get; set; }
        public string UserId { get; set; }
        public string RefCode { get; set; }
        public string ReferralUserType { get; set; }
    }
}
