//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralCommission
    {
        public int ReferralCommissionId { get; set; }
        public Nullable<int> ReferralTypeId { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> Commission2 { get; set; }
        public Nullable<int> ExpireValues { get; set; }
    }
}
