//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUser
    {
        public string rUserId { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> DeliveryAgentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DeliveryAgent DeliveryAgent { get; set; }
        public virtual UserType UserType1 { get; set; }
        public virtual WineShop WineShop { get; set; }
    }
}
