//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketDetails()
        {
            this.Ticket_DocumentDetails = new HashSet<Ticket_DocumentDetails>();
        }
    
        public long TicketID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Issue { get; set; }
        public Nullable<int> TicketStatusID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_DocumentDetails> Ticket_DocumentDetails { get; set; }
    }
}
