//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketCommunicationHistory
    {
        public long ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string GroupID { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
