//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RainbowWine.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProductSearch
    {
        public int ProductID { get; set; }
        public int ShopID { get; set; }
        public string ProductCategory { get; set; }
        public string Search { get; set; }
    }
}
